#!/usr/bin/php
<?php

if (php_sapi_name() !== 'cli') {
    exit;
}

require __DIR__ . '/vendor/autoload.php';

use Minicli\App;
use App\Service\CrawlerService;
use App\Service\DBService;

$config = require_once(__DIR__ . '/config.php');
$app = new App($config);

$app->addService('crawler', new CrawlerService());
$app->addService('db', new DBService());

$app->runCommand($argv);
