#!/usr/bin/php
<?php

if (php_sapi_name() !== 'cli') {
    exit;
}

require __DIR__ . '/vendor/autoload.php';

use Minicli\App;
use App\Service\CrawlerService;

$app = new App([
    'app_path' => __DIR__ . '/app/Command',
    'theme' => '\Unicorn'
]);

$app->addService('crawler', new CrawlerService());

$app->runCommand($argv);
